version: '3.8'

services:
  # Service untuk backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: herca-backend
    restart: always
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_URL=http://hercabe.kresnansite.my.id
      - APP_ENV=production
      # Tambahkan variabel lingkungan lain yang dibutuhkan
    networks:
      - herca_network

  # Service untuk frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: herca-frontend
    restart: always
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - herca_network

  # Service Nginx sebagai reverse proxy
  nginx:
    image: nginx:alpine
    container_name: herca-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - herca_network

networks:
  herca_network:
    driver: bridge