FROM php:8.4-apache

RUN apt-get update && apt-get install -y \
    git curl unzip zip libpng-dev libonig-dev libxml2-dev libzip-dev \
    && docker-php-ext-install pdo pdo_mysql mbstring zip exif pcntl

RUN a2enmod rewrite

WORKDIR /var/www/herca/

COPY backend/ /var/www/herca/

RUN chown -R www-data:www-data /var/www/herca/ \
    && chmod -R 755 /var/www/herca/

COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer
RUN composer install --no-interaction --optimize-autoloader

EXPOSE 9000
