name: 🚀 CI/CD Laravel Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: 📦 Checkout Code
        uses: actions/checkout@v4

      - name: 🔐 Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🛠 Build Docker Image for Laravel
        run: docker build -t kresnandaf/laravel-herca:latest .

      - name: 📤 Push Docker Image to DockerHub
        run: docker push kresnandaf/laravel-herca:latest

      - name: 🚢 Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔁 Pulling latest Docker image..."
            docker pull kresnandaf/laravel-herca:latest

            echo "🛑 Stopping and removing old container..."
            docker stop laravel-herca || true
            docker rm laravel-herca || true

            echo "📂 Creating necessary directories..."
            mkdir -p /var/www/herca/storage
            mkdir -p /var/www/herca/bootstrap/cache

            echo "🚀 Running new Laravel container..."
            docker run -d \
              --name laravel-herca \
              --restart unless-stopped \
              -p "${{ secrets.PORT }}":3000 \
              -v /var/www/herca/storage:/var/www/html/storage \
              -v /var/www/herca/bootstrap/cache:/var/www/html/bootstrap/cache \
              kresnandaf/laravel-herca:latest

            echo "✅ Deployment finished!"
